### ISSUE TITLE
http://vis.supstat.com - Server Not Found

### ISSUE THREAD

**Issue by MarcinKosinski** [supstat/vistat#14]
@yihui your site does not show anything http://vis.supstat.com

**Comment by MarcinKosinski** [comment]
Go Vistat here http://animation.yihui.name/ also does not work

**Comment by yihui** [comment]
@casunlight You need to create a CNAME record for vis.supstat.com pointing to supstat.github.io

**Comment by casunlight** [comment]
Dear ZEYU,
Could you please handle Yihui's request? Thanks!

**Comment by casunlight** [comment]
Hi Vivian,

I need more information to do that. There is no github user called supstat
so that's why supstat.github.io gives you a 404 error. If you want to
redirect vis.supstat.com to the github page, you could change the settings
at the domain provider website of supstat.com.

Best,
Zeyu

**Comment by yihui** [comment]
It is not redirection. You just need to create a CNAME record as I said.

**Comment by MarcinKosinski** [comment]
It's a file like this one
https://github.com/MarcinKosinski/MarcinKosinski.github.io/blob/master/CNAME

**Comment by yulijia** [comment]
A step by step guide to fixing the domain resolution bug:
1. login to your domain (supstat.com) registrar, I think it may be [name.com](http://www.name.com).
2. Delete or change **SOA record** to  **CNAME record**  as shown in the figure below. The figure I got from another domain registrar namesilo.com.
3. After step 2, you could check settings with command line `dig vis.supstat.com` in terminal ( you should get a terminal output with **CNAME record**, but if you check vis.supstat.com right now, you would get **SOA record** ).
![Imgur](http://i.imgur.com/oZ384Pt.png)

**Comment by yulijia** [comment]
Fixed. http://vis.supstat.com
